### ISSUE TITLE
depth function can only return 1

### ISSUE THREAD

**Issue by ltsstar** [truprecht/prog-hs#1]
https://github.com/truprecht/prog-hs/blob/b86ef572bd8d6debd39d608eee290ed86cc37f8f/tut03/tut03.hs#L10

Running the function on the given example tree returns 1.

> *Main> depth (Branch 0 (Branch 1 (Branch 8 (Leaf 10) (Leaf 12)) (Leaf 3)) (Branch 3 (Leaf 6) (Leaf 4)))
> 1

**Comment by ltsstar** [comment]
Referenced line should be:

`depth (Branch _ t1 t2) = min (depth t1) (depth t2) + 1`

**Comment by truprecht** [comment]
Thanks!
